name: Echo Text Jobs

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Text Job 1
        run: echo "This is Job 1"

  job2:
    runs-on: ubuntu-latest

    needs: job1

    steps:
      - name: Wait for 200 seconds
        run: sleep 200

      - name: Echo Text Job 2
        run: echo "Job 1 completed, and now this is Job 1"
